apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-frontend-app
  template:
    metadata:
      labels:
        app: my-frontend-app
    spec:
      containers:
      - name: my-frontend-app
        image: ${{ steps.ecr-image-uri.outputs.image-uri }} # Placeholder for the image URI
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-app-service
spec:
  selector:
    app: my-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
